apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http.yaml
  - service.yaml

configMapGenerator:
  - name: app-config
    files:
      - configmap/

images:
  - name: app
    newTag: latest